### ISSUE TITLE
Color picker option

### ISSUE THREAD

**Issue by sttrebo** [sadmice/joplin-plugin-text-colorize#1]
Not sure if you're taking requests, but integrating a color picker would be great.  Something like this: 
[Color picker](https://github.com/Toinane/colorpicker) 

Thanks

**Comment by sadmice** [comment]
That's in the plans. I'll do it soon.

**Comment by sadmice** [comment]
It's now implemented. [Release v1.1.0](https://github.com/sadmice/Joplin-Plugin-Text-Colorize/releases/tag/v1.1.0)
