### ISSUE TITLE
plugin get not activated with CTRL SHIFT C

### ISSUE THREAD

**Issue by epepping** [sadmice/joplin-plugin-text-colorize#10]
I installed the plugin in latest Joplin version. Installation was successful. Short cut to color text after installation does not give the pop-up.
Joplin version : 2.2.19
Text colorize  1.2.3

**Comment by sadmice** [comment]
Hello. Did you mean 2.12.19?
It's working fine on my end. Maybe there's something else tied to that shortcut? You can tweak the shortcut in `Tools > Options > Text Colorize`. If that doesn't do the trick, can you see if you're able to open the popup manually through `Tools > Text Colorize > Text Colorize`?

**Comment by epepping** [comment]
Today is seems to work.
Restarted Joplin Twice.

Thnks


Met vriendelijke groet,

Erik Pepping
Tel : 06-54686531



Op ma 27 nov 2023 om 11:35 schreef Sadmice ***@***.***>:
