### ISSUE TITLE
Not working in Rich Text Editor

### ISSUE THREAD

**Issue by Ahmad-AlDeeb** [sadmice/joplin-plugin-text-colorize#11]
Hey there,

I like the plugin but I thought it would work in both editors (Rich Text & Markdown), but it seems to be only working with Markdown editor.
or It doesn't support the Rich Text Editor in first place?

Thanks

## About Joplin
Joplin 2.13.15 (prod, win32)

Client ID: afbcbeeaead9406f84a5294abd55beae
Sync Version: 3
Profile Version: 44
Keychain Supported: Yes

Revision: 7d2c1c0

Text Colorize: 1.2.5

**Comment by sadmice** [comment]
Hi.

It's due to Rich Text limitations, as mentioned in the repository's README.
