### ISSUE TITLE
the text marked with color is not saved

### ISSUE THREAD

**Issue by StillDan** [sadmice/joplin-plugin-text-colorize#3]
the text marked with color is not saved

**Comment by sadmice** [comment]
Could you please clarify your issue? Do you select text, apply color, and the selected text is deleted? If so, indicate the specific steps of your actions.

**Comment by StillDan** [comment]
Watch the video in the attachment please
https://disk.yandex.ru/d/NSzZCZOwOxGwpg

**Comment by sadmice** [comment]
In the first part of the video you are in the Markdown Viewer, here you cannot edit your notes. To enter the Markdown Editor, press `Ctrl + l` or click `View` - `Toggle editor layout`

In the second part you switch from Markdown to Rich Text Editor, but Joplin stores all notes in Markdown format and HTML formatting cannot be converted from Rich Text to Markdown, this is a limitation of the Rich Text Editor.

Quote from https://joplinapp.org/rich_text_editor/
> If a note is of 'Markup - Markdown' and contains HTML formatting, this may be lost when editing in the Rich Text editor as it cannot be converted to Markdown.
