### ISSUE TITLE
colour change can't be saved

### ISSUE THREAD

**Issue by fanxiaomu31569** [sadmice/joplin-plugin-text-colorize#5]
Thanks for your great job! I'm a rookie in programming, and I enjoy your script's functions. It helps me quickly highlight my note content. However, I encountered one big issue after changing the text colour using your script. When I saved the colour change and switched back, the text colour reset to default automatically. Is this appear correct?

**Comment by UrfinJuice11** [comment]
Thanks for the plugin!
But the same issue. Also, suppose it would be a good addition to switch back to the original color of the text.

**Comment by sadmice** [comment]
@Senaxios 
Sorry, could you please elaborate on your issue or, ideally, make a short video?

@UrfinJuice11 
Switch back to the original color is a good idea, I will implement it.

**Comment by phirestalker** [comment]
If it is the same as what is happening for me, the color of the text reverts to original color of text when you switch to markdown view. I would have expected it to save the HTML tags so they would show up in the markdown.

**Comment by rubenafo** [comment]
Thanks for the plugin, it's very handy. 
I mostly use the Markdown editor and have the same issue, background color is rendered fine but once I change note, color is gone when I go back to the original note.

**Comment by sadmice** [comment]
I think you're referring to the Rich Text Editor.
HTML formatting cannot be converted from Rich Text to Markdown
I addressed this question in issue #3

**Comment by phirestalker** [comment]
Noted. I guess the rich text editor makes this plugin useless to me. Thanks for the reply.
