### ISSUE TITLE
Multi-cursor support

### ISSUE THREAD

**Issue by amzon-ex** [sadmice/joplin-plugin-text-colorize#6]
Joplin has multi-cursor support - i.e. you can Ctrl-Click in multiple places and insert text at those locations simultaneously. But when I try to colour the text at all of these locations together (by selecting all the text at once) the extension just copies the first instance of the text to each location. Can this be fixed?

**Comment by sadmice** [comment]
I’m aware of this problem. I use `joplin.commands.execute("selectedText")` and it only picks up the first selection. I'm not sure if this can be fixed. If anyone has a solution, I would really appreciate it.

**Comment by sadmice** [comment]
Fixed in [v1.2.2](https://github.com/sadmice/joplin-plugin-text-colorize/releases/tag/v1.2.2)
