### ISSUE TITLE
Unable to reserve font color. 

### ISSUE THREAD

**Issue by g2mXagent** [sadmice/joplin-plugin-text-colorize#7]
Unable to reserve font color. 
When I color the text, go to Markdown edit mode, or go to another document, the color will disappear.

Joplin 2.8.8
Windows 10

**Comment by sadmice** [comment]
HTML formatting cannot be converted from Rich Text to Markdown.

Please, read https://github.com/sadmice/joplin-plugin-text-colorize/issues/3#issuecomment-1100213701. I also added a warning in the README to avoid further questions about this.
