### ISSUE TITLE
Color text plugin does not work how I would like it to. 

### ISSUE THREAD

**Issue by RustyRover** [sadmice/joplin-plugin-text-colorize#9]
I have just started to use Joplin. It think it is the best lists app I have seen. I installed your text plugin plugin. The only way I can make it work is to use the shortcut on text in markdown. I would just like to use it in the text editor, because it would be quicker and easier. Is this a bug, or a limitation or did I do something wrong? Please tell me how to correct this without writing any code. It's not that I cannot write code (I did a lot of programming in several different languages years ago); it's just that I'm an old geezer and, while I am pretty good with Windows and MS products, I just don't want to go back to school again at my age. 

Please help me. Thanks.

**Comment by sadmice** [comment]
I've added toolbar button in [v1.2.4](https://github.com/sadmice/joplin-plugin-text-colorize/releases/tag/v1.2.4)
